<?php

class Settings {
    static public $lang;

    static public $breakPoints = [
        '2XL' => '1536px',
        'XL' => '1280px',
        'L' => '1024px',
        'M' => '768px',
        'S' => '640px',
        'XS' => '480px',
    ];

    static public $pseudoClasses = [
        'active',
        'after',
        'backdrop',
        'before',
        'checked',
        'default',
        'disabled',
        'empty',
        'even',
        'first-child',
        'first-letter',
        'first-line',
        'first-of-type',
        'first',
        'focus-not-visible',
        'focus-visible',
        'focus-within',
        'focus',
        'grammar-error',
        'group-focus',
        'group-hover',
        'hover',
        'in-range',
        'indeterminate',
        'invalid',
        'last-child',
        'last-of-type',
        'last',
        'marker',
        'not',
        'nth-child',
        'nth-last-child',
        'nth-last-of-type',
        'nth-of-type',
        'odd',
        'only-child',
        'only-of-type',
        'optional',
        'out-of-range',
        'placeholder-shown',
        'placeholder',
        'read-only',
        'read-write',
        'required',
        'root',
        'search-match',
        'selection',
        'spelling-error',
        'target',
        'valid',
        'visited',
    ];
    
}